Allow for cooperative release of funds
comit-network/xmr-btc-swap pull request #1676
Opened 2024-06-10 16:57 UTC by patrini32

Should close #693. Introduces new logic for the BtcPunished state.

2024-06-10 17:08 UTC, patrini32 commented
Oh, latest commit broke the code.

2024-06-11 15:51 UTC, patrini32 commented on swap/src/protocol/bob/state.rs
I added this function to State3 because it's possible that Bob's database is in incorrect state.

2024-06-12 13:50 UTC, binarybaron commented
@patrini32 Can you give @einliterflasche access to your fork of this repository? He has some improvements for this PR and that way he'll be able to push directly to your branch.

2024-06-12 14:06 UTC, patrini32 commented
> @patrini32 Can you give @Einliterflasche access to your fork of this repository? He has some improvements for this PR and that way he'll be able to push directly to your branch.

Sure.

2024-06-12 14:06 UTC, binarybaron commented
> > @patrini32 Can you give @Einliterflasche access to your fork of this repository? He has some improvements for this PR and that way he'll be able to push directly to your branch.
> 
> Sure.

thanks :)

2024-06-12 14:08 UTC, patrini32 commented
Sent invite

2024-06-12 14:12 UTC, Einliterflasche commented
thanks! I think using `let else` really pays off here

2024-06-12 14:14 UTC, patrini32 commented
> thanks! I think using `let else` really pays off here

Thank you for refactoring it.

2024-06-12 14:40 UTC, binarybaron commented on swap/src/api/request.rs
> +                tracing::info!("Asking Alice to reveal xmr key to us.");
nitpick: Remove the dot at the end

2024-06-12 14:41 UTC, patrini32 commented on swap/src/api/request.rs
> +                tracing::info!("Asking Alice to reveal xmr key to us.");
Okay

2024-06-12 14:41 UTC, binarybaron commented on swap/src/api/request.rs
> +                        tracing::info!("Alice revealed xmr key to us, redeeming xmr...");
same here xmr -> XMR

2024-06-12 14:45 UTC, binarybaron requested changes
This looks pretty good! I commented two small nitpicks. And two things we need to get done before we merge this:
1. Alice should return a proper error to Bob if she cannot provide the secret key (@Einliterflasche is working on this)
2. We want to add logic to the Bobs state machine for him to automatically try to cooperative redeem if he ends up in BtcPunished

2024-06-12 14:47 UTC, patrini32 commented
> This looks pretty good! I commented two small nitpicks. And two things we need to get done before we merge this:
> 
> 1. Alice should return a proper error to Bob if she cannot provide the secret key (@Einliterflasche is working on this)
> 2. We want to add logic to the Bobs state machine for him to automatically try to cooperative redeem if he ends up in BtcPunished

I implemented 2 initially, but it required changes to database.

2024-06-12 18:47 UTC, patrini32 commented
> This looks pretty good! I commented two small nitpicks. And three things we need to get done before we merge this:
> 
> 1. Alice should return a proper error to Bob if she cannot provide the secret key (@Einliterflasche is working on this)
> 2. We want to add logic to the Bobs state machine for him to automatically try to cooperative redeem if he ends up in BtcPunished
> 3. Think about adding the secret key to the BtcPunished state of Alice and also add the data needed for Bob to his states such that we dont need to iterate through all the states to find the data we need. If we do this, we should make this backwards compatible by possibly creating a migration script (add data all the required data to the states if they were created before the update). I think it's if we think about which option is best before implementing it.

I implemented 2, but it requires changes to multiple BobStates, because state3 doesn't contain monero_wallet_restore_blockheight, so we can't just change State6.

2024-06-12 18:48 UTC, patrini32 commented
Hmm, actually, what if pass monero_wallet_restore_blockheight to cancel?

2024-06-12 19:43 UTC, patrini32 commented
> This looks pretty good! I commented two small nitpicks. And three things we need to get done before we merge this:
> 
> 1. Alice should return a proper error to Bob if she cannot provide the secret key (@Einliterflasche is working on this)
> 2. We want to add logic to the Bobs state machine for him to automatically try to cooperative redeem if he ends up in BtcPunished
> 3. Think about adding the secret key to the BtcPunished state of Alice and also add the data needed for Bob to his states such that we dont need to iterate through all the states to find the data we need. If we do this, we should make this backwards compatible by possibly creating a migration script (add data all the required data to the states if they were created before the update). I think it's if we think about which option is best before implementing it.

I implemented 2 and added new test for it.
@binarybaron

2024-06-14 17:20 UTC, patrini32 commented
> This looks pretty good! I commented two small nitpicks. And three things we need to get done before we merge this:
> 
> 1. Alice should return a proper error to Bob if she cannot provide the secret key (@Einliterflasche is working on this)
> 2. We want to add logic to the Bobs state machine for him to automatically try to cooperative redeem if he ends up in BtcPunished
> 3. Think about adding the secret key to the BtcPunished state of Alice and also add the data needed for Bob to his states such that we dont need to iterate through all the states to find the data we need. If we do this, we should make this backwards compatible by possibly creating a migration script (add data all the required data to the states if they were created before the update). I think it's if we think about which option is best before implementing it.

Implemented all of these, can you review, please? @binarybaron

2024-06-14 17:24 UTC, patrini32 commented on migrate/src/main.rs
> +    println!("Copying {path_str} to {path_str}.original...");
I don't think that we need tracing there.

2024-06-17 13:14 UTC, patrini32 commented
@binarybaron, is it okay to use sql migrations?

2024-06-18 09:15 UTC, patrini32 commented
> > @binarybaron, is it okay to use sql migrations?
> 
> Yes that's fine. I'll have to review the SQL in depth. Can you add comments to the SQL query?

Sure

2024-06-18 09:27 UTC, patrini32 commented
> > @binarybaron, is it okay to use sql migrations?
> 
> Yes that's fine. I'll have to review the SQL in depth. Can you add comments to the SQL query?

Should I add comments to all SQL queries or just the first two? (Others are copies of these).

2024-06-18 10:01 UTC, binarybaron requested changes

2024-06-18 10:50 UTC, patrini32 commented on swap/src/protocol/bob/swap.rs
> +        if matches!(current_state, BobState::BtcPunished { .. }) {
Is it okay to add this to run_until or should this function be more general?

2024-06-18 10:54 UTC, binarybaron commented
@delta1 Do you have time to give this a review?

2024-06-18 11:27 UTC, patrini32 commented
Oh, sorry, @binarybaron, can you rerun the CI, I fixed tests.

2024-06-18 11:50 UTC, patrini32 commented
> Oh, sorry, @binarybaron, can you rerun the CI? I fixed tests.
Uh, that's weird. I ran this test several times and it didn't fail.

2024-06-18 12:01 UTC, patrini32 commented
@binarybaron, can you run CI again, I think there's some nondeterminism there.

2024-06-19 10:19 UTC, binarybaron commented
Can you also add some more general comments to the SQL migration file? The ones you added are good but are very specific. They are quite hard to understand without having as much context.

For example: "This query adds the new state3 attribute that has been added in PR..."

2024-06-19 10:35 UTC, patrini32 commented
> Can you also add some more general comments to the SQL migration file? The ones you added are good but are very specific. They are quite hard to understand without having as much context.
> 
> For example: "This query adds the new state3 attribute that has been added in PR..."

Done.

2024-06-22 13:51 UTC, patrini32 commented
Are there any other changes I should make?

2024-06-27 12:04 UTC, patrini32 commented
> After letting a swap go to BtcPunished (with a CLI without these changes applied) and then running `swap --testnet history` gives an error even after the migrations have been applied.
> 
> ```
> ./target/debug/swap --testnet history
> Logging initialized to /Users/****/Library/Application Support/xmr-btc-swap/cli/testnet/logs
> Error: missing field `v` at line 1 column 3327
> ```

Hmm, that's odd, it worked when I tested it.

2024-06-27 12:14 UTC, binarybaron commented
> > After letting a swap go to BtcPunished (with a CLI without these changes applied) and then running `swap --testnet history` gives an error even after the migrations have been applied.
> > ```
> > ./target/debug/swap --testnet history
> > Logging initialized to /Users/****/Library/Application Support/xmr-btc-swap/cli/testnet/logs
> > Error: missing field `v` at line 1 column 3327
> > ```
> 
> Hmm, that's odd, it worked when I tested it.

I'll investigate. Are you added the new v attribute to every state6 attribute in every state?

2024-06-27 12:15 UTC, patrini32 commented
> > > After letting a swap go to BtcPunished (with a CLI without these changes applied) and then running `swap --testnet history` gives an error even after the migrations have been applied.
> > > ```
> > > ./target/debug/swap --testnet history
> > > Logging initialized to /Users/****/Library/Application Support/xmr-btc-swap/cli/testnet/logs
> > > Error: missing field `v` at line 1 column 3327
> > > ```
> > 
> > 
> > Hmm, that's odd, it worked when I tested it.
> 
> I'll investigate. Are you added the new v attribute to every state6 attribute in every state?
Yes

2024-06-27 13:03 UTC, patrini32 commented
> > > After letting a swap go to BtcPunished (with a CLI without these changes applied) and then running `swap --testnet history` gives an error even after the migrations have been applied.
> > > ```
> > > ./target/debug/swap --testnet history
> > > Logging initialized to /Users/****/Library/Application Support/xmr-btc-swap/cli/testnet/logs
> > > Error: missing field `v` at line 1 column 3327
> > > ```
> > 
> > 
> > Hmm, that's odd, it worked when I tested it.
> 
> I'll investigate. Are you sure added the new v attribute to every state6 attribute in every state?

I tested it now. It works.

2024-06-28 19:07 UTC, binarybaron commented
Can you use an enum for the errors instead of a string?

2024-06-28 19:49 UTC, patrini32 commented
> Can you use an enum for the errors instead of a string?

Do you want to parse errors on the cli side?

2024-07-01 15:09 UTC, binarybaron commented
> > Can you use an enum for the errors instead of a string?
> 
> Do you want to parse errors on the cli side?

You can use `thiserror`

For example see how it is being used in `swap/src/network/swap_setup/alice.rs`

```rust
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("ASB is running in resume-only mode")]
    ResumeOnlyMode,
    #[error("Amount {buy} below minimum {min}")]
    AmountBelowMinimum {
        min: bitcoin::Amount,
        buy: bitcoin::Amount,
    },
    #[error("Amount {buy} above maximum {max}")]
    AmountAboveMaximum {
        max: bitcoin::Amount,
        buy: bitcoin::Amount,
    },
    #[error("Unlocked balance ({balance}) too low to fulfill swapping {buy}")]
    BalanceTooLow {
        balance: monero_rpc::wallet::GetBalance,
        buy: bitcoin::Amount,
    },
    #[error("Failed to fetch latest rate")]
    LatestRateFetchFailed(#[source] Box<dyn std::error::Error + Send + Sync + 'static>),
    #[error("Failed to calculate quote")]
    SellQuoteCalculationFailed(#[source] anyhow::Error),
    #[error("Blockchain networks did not match, we are on {asb:?}, but request from {cli:?}")]
    BlockchainNetworkMismatch {
        cli: BlockchainNetwork,
        asb: BlockchainNetwork,
    },
}
```

2024-07-01 21:21 UTC, binarybaron commented on swap/migrations/20240615140942_btcpunished_update.sql
> +                                states.state, '$.Bob.BtcCancelled'
We can enter the `BtcPunished` state without ever entering the `BtcCancelled` state. Can you extract this data from somewhere else?

2024-07-01 21:21 UTC, binarybaron requested changes
sql query

2024-07-11 07:23 UTC, binarybaron commented
@Einliterflasche @delta1 Can you give this another glance before I merge this?

2024-07-11 12:05 UTC, delta1 commented
@binarybaron i will review tomorrow

2024-07-15 08:00 UTC, delta1 approved these changes
LGTM

2024-07-15 08:00 UTC, merged