add --refund-to-internal-wallet flag
comit-network/xmr-btc-swap pull request #1709
Opened 2024-07-09 18:52 UTC by Einliterflasche

2024-07-09 18:53 UTC, Einliterflasche commented
This change isn't as straight forward as one would think it would be because the the `structopt` proc macro doesn't seem to work as intended.

2024-07-09 19:36 UTC, binarybaron requested changes

2024-07-09 19:36 UTC, binarybaron commented on swap/src/api.rs
> +    pub fn bitcoint_wallet(&self) -> Option<Arc<bitcoin::Wallet>> {
Typo

2024-07-09 20:16 UTC, Einliterflasche commented
The flag is now added, but the help dialogue for `swap buy-xmr` now shows:

```rust
Error: error: The following required arguments were not provided:
    --change-address <bitcoin-change-address>
    --receive-address <monero-receive-address>
    --refund-to-internal-wallet
    --seller <seller>

USAGE:
    swap buy-xmr --change-address <bitcoin-change-address> --receive-address <monero-receive-address> --refund-to-internal-wallet --seller <seller> --tor-socks5-port <tor-socks5-port>
```

even though the command works as intended (with `--refund-to-internal-wallet`, `--change-address` isn't required). Using both flags correctly gives `Error: error: The argument '--change-address <bitcoin-change-address>' cannot be used with '--refund-to-internal-wallet'`

2024-07-09 20:21 UTC, Einliterflasche commented
lmao did you just merge into my branch?

2024-07-09 21:40 UTC, Einliterflasche commented
w8 i still have to test 💀

2024-07-09 23:38 UTC, Einliterflasche commented
I added a logging message and tested the flag. Do you think we need a unit test? I don't really think so.

2024-07-10 07:27 UTC, delta1 commented
Does this require a flag? change-address could be optional, and if it's excluded then we can default to using the internal wallet (with a log message and/or confirmation)

2024-07-10 09:59 UTC, delta1 commented
Yep I think what I've suggested is a better UX and should just be communicated to the user, and documented in the changelog/docs. It's actually always felt painful to have to supply a change address.

2024-07-10 10:07 UTC, Einliterflasche commented
Very well. It seems that clippy agrees with you ;) 

```rust
error: field `refund_to_internal_wallet` is never read
   --> swap/src/cli/command.rs:336:9
    |
314 |     BuyXmr {
    |     ------ field in this variant
...
336 |         refund_to_internal_wallet: bool,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`
```

I'll push what you suggested shortly.

2024-07-10 10:08 UTC, delta1 commented
Thanks @Einliterflasche ! Hopefully @binarybaron agrees :)

2024-07-10 10:30 UTC, binarybaron commented
> Yep I think what I've suggested is a better UX and should just be communicated to the user, and documented in the changelog/docs. It's actually always felt painful to have to supply a change address.

I agree 👍

2024-07-10 11:55 UTC, delta1 commented on swap/src/cli/command.rs
> +                        "No --change-address supplied. Incase of a refund funds will be sent to internal wallet."
```suggestion
                        "No --change-address supplied. Any change will be received to the internal wallet."
```

2024-07-10 11:56 UTC, delta1 commented
Please update the changelog and any docs that refer to change-address

2024-07-11 07:19 UTC, binarybaron commented
LGTM!

2024-07-11 07:19 UTC, merged