Wait for wallet to catch up instead of block generation
comit-network/xmr-btc-swap pull request #248
Opened 2021-03-01 06:18 UTC by da-kami

The monero harness wallet always starts a miner that mines new blocks every second.
This can conflict with additionally triggering block generation  and cause this error:

```
monero_rpc::rpc::monerod: generate blocks response: {
  "error": {
    "code": -7,
    "message": "Block not accepted"
  },
  "id": "1",
  "jsonrpc": "2.0"
}
```

Since the miner is generating blocks anyway we can wait for the wallet to catch up.
Refresh is done upon querying the balance, thus the refresh calls were removed.

---

Note: we could also opt for starting the miner optionally. This would make this test more efficient, but is a more intrusive change, thus I opted for this fix for now.

2021-03-01 22:49 UTC, thomaseizinger requested changes
Thank you! Just one comment :)

2021-03-01 22:49 UTC, thomaseizinger commented on monero-harness/tests/wallet.rs
> +        sleep(Duration::from_secs(1));
This should be a `tokio::time::sleep`.

2021-03-02 01:34 UTC, rishflab approved these changes

2021-03-02 02:19 UTC, thomaseizinger approved these changes

2021-03-02 03:56 UTC, thomaseizinger commented
bors r+

2021-03-02 04:06 UTC, merged