Allow withdrawing and viewing of the bitcoin balance on swap-cli
comit-network/xmr-btc-swap pull request #704
Opened 2021-08-29 16:57 UTC by devbordecraft

Same mechanics of the ASB but on swap-cli as discussed in #694

2021-08-30 04:56 UTC, rishflab commented
hi thanks for the PR, this was pretty high priority on our list of things to do.

There are some formatting issues which can be fixed with
`dprint fmt`

install dprint
https://dprint.dev

2021-08-30 19:36 UTC, devbordecraft commented
Fix is pushed

2021-08-30 22:58 UTC, rishflab approved these changes
Thanks again!

2021-08-31 02:55 UTC, thomaseizinger requested changes
Thanks for the contribution!

Two minor things to be addressed. Can you also squash all commits into one while you are at it?

2021-08-31 02:55 UTC, thomaseizinger commented on CHANGELOG.md
> +  See issue https://github.com/comit-network/xmr-btc-swap/issues/694
This should go under `## Added` rather than `## Fixed`.

2021-08-31 02:55 UTC, thomaseizinger commented on swap/src/cli/command.rs
> +}
We already have `validate_bitcoin_address`, lets use that instead.

2021-09-01 01:46 UTC, rishflab commented
bors r+

2021-09-01 02:02 UTC, merged