Use upstream libp2p
comit-network/xmr-btc-swap pull request #820
Opened 2021-10-12 23:01 UTC by rishflab

todo: remove ping

2021-10-13 00:03 UTC, rishflab commented
the rendezvous `unit` test failed locally. There were no failures in CI and im pretty sure it would of run. Investigating... may just be a one off failure

2021-10-13 03:32 UTC, thomaseizinger commented
It is not passing CI either but hanging forever, I will have a look!

2021-10-13 06:08 UTC, thomaseizinger commented on swap/src/network/cbor_request_response.rs
>              .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
Also get rid of this.

2021-10-13 06:08 UTC, thomaseizinger commented on swap/src/network/json_pull_codec.rs
>              .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
And here.

2021-10-14 00:02 UTC, thomaseizinger requested changes
Thanks! Couple of comments :)

2021-10-14 00:02 UTC, thomaseizinger commented on swap/src/cli.rs
> +    impl NetworkBehaviourEventProcess<libp2p::rendezvous::client::Event> for StaticQuoteAsbBehaviour {
Doing `use libp2p::rendezvous;` would go  along way in this file as well.

2021-10-14 00:02 UTC, thomaseizinger commented on swap/src/network/cbor_request_response.rs
>              .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
Can we not use `?` here?

2021-10-14 00:25 UTC, rishflab commented on swap/src/cli.rs
>          });
its only constructed once and in a test. not sure if worth it

2021-10-14 01:11 UTC, rishflab commented
bors r+

2021-10-14 01:40 UTC, merged